### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by karmenzupancic** [karmenzupancic/APPR-2018-19#1]
Zdravo!
Meni se zemljevid v poročilu izriše, vendar manjkajo določene države. 
Kaj je problem?

**Comment by jaanos** [comment]
Namesto `right_join` uporabi `left_join` - ta ohrani vse vrstice iz prve podane razpredelnice (v tem primeru zemljevida); države, za katere ni podatkov, bodo tako prikazane v sivi barvi. Lahko pa bi seveda tudi zamenjala vrstni red razpredelnic in stolpcev pri parametru `by`.
